/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PenaRouteImport } from './routes/pena'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PedidoPenaTokenRouteImport } from './routes/pedido-pena.$token'
import { Route as ConfirmarTokenRouteImport } from './routes/confirmar.$token'
import { Route as AppNuevaRouteImport } from './routes/app.nueva'
import { Route as AppMatriculasRouteImport } from './routes/app.matriculas'
import { Route as AppHistorialRouteImport } from './routes/app.historial'
import { Route as AppFamiliasRouteImport } from './routes/app.familias'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppAjustesRouteImport } from './routes/app.ajustes'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminTalleresRouteImport } from './routes/admin.talleres'

const PenaRoute = PenaRouteImport.update({
  id: '/pena',
  path: '/pena',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PedidoPenaTokenRoute = PedidoPenaTokenRouteImport.update({
  id: '/pedido-pena/$token',
  path: '/pedido-pena/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarTokenRoute = ConfirmarTokenRouteImport.update({
  id: '/confirmar/$token',
  path: '/confirmar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNuevaRoute = AppNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => AppRoute,
} as any)
const AppMatriculasRoute = AppMatriculasRouteImport.update({
  id: '/matriculas',
  path: '/matriculas',
  getParentRoute: () => AppRoute,
} as any)
const AppHistorialRoute = AppHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AppRoute,
} as any)
const AppFamiliasRoute = AppFamiliasRouteImport.update({
  id: '/familias',
  path: '/familias',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAjustesRoute = AppAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTalleresRoute = AdminTalleresRouteImport.update({
  id: '/talleres',
  path: '/talleres',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pena': typeof PenaRoute
  '/admin/talleres': typeof AdminTalleresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/ajustes': typeof AppAjustesRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/familias': typeof AppFamiliasRoute
  '/app/historial': typeof AppHistorialRoute
  '/app/matriculas': typeof AppMatriculasRoute
  '/app/nueva': typeof AppNuevaRoute
  '/confirmar/$token': typeof ConfirmarTokenRoute
  '/pedido-pena/$token': typeof PedidoPenaTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pena': typeof PenaRoute
  '/admin/talleres': typeof AdminTalleresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/ajustes': typeof AppAjustesRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/familias': typeof AppFamiliasRoute
  '/app/historial': typeof AppHistorialRoute
  '/app/matriculas': typeof AppMatriculasRoute
  '/app/nueva': typeof AppNuevaRoute
  '/confirmar/$token': typeof ConfirmarTokenRoute
  '/pedido-pena/$token': typeof PedidoPenaTokenRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pena': typeof PenaRoute
  '/admin/talleres': typeof AdminTalleresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/ajustes': typeof AppAjustesRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/familias': typeof AppFamiliasRoute
  '/app/historial': typeof AppHistorialRoute
  '/app/matriculas': typeof AppMatriculasRoute
  '/app/nueva': typeof AppNuevaRoute
  '/confirmar/$token': typeof ConfirmarTokenRoute
  '/pedido-pena/$token': typeof PedidoPenaTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/pena'
    | '/admin/talleres'
    | '/admin/usuarios'
    | '/app/ajustes'
    | '/app/clientes'
    | '/app/familias'
    | '/app/historial'
    | '/app/matriculas'
    | '/app/nueva'
    | '/confirmar/$token'
    | '/pedido-pena/$token'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pena'
    | '/admin/talleres'
    | '/admin/usuarios'
    | '/app/ajustes'
    | '/app/clientes'
    | '/app/familias'
    | '/app/historial'
    | '/app/matriculas'
    | '/app/nueva'
    | '/confirmar/$token'
    | '/pedido-pena/$token'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/pena'
    | '/admin/talleres'
    | '/admin/usuarios'
    | '/app/ajustes'
    | '/app/clientes'
    | '/app/familias'
    | '/app/historial'
    | '/app/matriculas'
    | '/app/nueva'
    | '/confirmar/$token'
    | '/pedido-pena/$token'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PenaRoute: typeof PenaRoute
  ConfirmarTokenRoute: typeof ConfirmarTokenRoute
  PedidoPenaTokenRoute: typeof PedidoPenaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pena': {
      id: '/pena'
      path: '/pena'
      fullPath: '/pena'
      preLoaderRoute: typeof PenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pedido-pena/$token': {
      id: '/pedido-pena/$token'
      path: '/pedido-pena/$token'
      fullPath: '/pedido-pena/$token'
      preLoaderRoute: typeof PedidoPenaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar/$token': {
      id: '/confirmar/$token'
      path: '/confirmar/$token'
      fullPath: '/confirmar/$token'
      preLoaderRoute: typeof ConfirmarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/nueva': {
      id: '/app/nueva'
      path: '/nueva'
      fullPath: '/app/nueva'
      preLoaderRoute: typeof AppNuevaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/matriculas': {
      id: '/app/matriculas'
      path: '/matriculas'
      fullPath: '/app/matriculas'
      preLoaderRoute: typeof AppMatriculasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historial': {
      id: '/app/historial'
      path: '/historial'
      fullPath: '/app/historial'
      preLoaderRoute: typeof AppHistorialRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/familias': {
      id: '/app/familias'
      path: '/familias'
      fullPath: '/app/familias'
      preLoaderRoute: typeof AppFamiliasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ajustes': {
      id: '/app/ajustes'
      path: '/ajustes'
      fullPath: '/app/ajustes'
      preLoaderRoute: typeof AppAjustesRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/talleres': {
      id: '/admin/talleres'
      path: '/talleres'
      fullPath: '/admin/talleres'
      preLoaderRoute: typeof AdminTalleresRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminTalleresRoute: typeof AdminTalleresRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTalleresRoute: AdminTalleresRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAjustesRoute: typeof AppAjustesRoute
  AppClientesRoute: typeof AppClientesRoute
  AppFamiliasRoute: typeof AppFamiliasRoute
  AppHistorialRoute: typeof AppHistorialRoute
  AppMatriculasRoute: typeof AppMatriculasRoute
  AppNuevaRoute: typeof AppNuevaRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAjustesRoute: AppAjustesRoute,
  AppClientesRoute: AppClientesRoute,
  AppFamiliasRoute: AppFamiliasRoute,
  AppHistorialRoute: AppHistorialRoute,
  AppMatriculasRoute: AppMatriculasRoute,
  AppNuevaRoute: AppNuevaRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PenaRoute: PenaRoute,
  ConfirmarTokenRoute: ConfirmarTokenRoute,
  PedidoPenaTokenRoute: PedidoPenaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
